os: Windows Server 2012 R2

environment:
  matrix:
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python27"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python --version
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - pip install -r dev-requirements.txt
  ## Use Chocolatey to install SWIG.
  # Only install swig if it isn't present (as a result of AppVeyor's caching).
  # SWIG 3.0.8 is the minimum required version, but it does not yet exist in
  # Chocolatey.
  - IF NOT EXIST C:\ProgramData\chocolatey\bin\swig.exe choco install swig --version 3.0.9 --yes --limit-output #> $null

build_script:
  - python setup.py sdist
  - python setup.py build

test_script:
  - python run_test.py
